server:
  port: 22100

spring:
  application:
    name: xc‐service‐base‐filesystem
  data:
    mongodb:
      database: xcFileSystem
      uri: mongodb://root:123456@192.168.175.132:27017
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB


fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.175.132:22122
  web-server-url: http://192.168.175.132:8888/