server:
  port: 31001
spring:
  application:
    name: xs-service-manage-cms
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: xcEdu
      username: root
      password: 123456
      authentication-database: admin


