server:
  port: ${port:31001} #服务端口
spring:
  application:
    name: xs-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:123456@127.0.0.1:27017
      database: xcEdu
  freemarker:
    cache: false
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id

