server:
  port: 31001
spring:
  application:
    name: xs-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:123456@127.0.0.1:27017
      database: xcEdu
  freemarker:
    cache: false


